site_name: CSE 12X Self-Placement

docs_dir: src

theme:
  name: null
  custom_dir: theme
  include_search_page: false
  search_index_only: false
  favicon: false

plugins:
    - macros:
        include_dir: includes